# Generated by Django 4.2.3 on 2023-07-08 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.CharField(choices=[('<1000', '< $1000'), ('1000-2000', '$1000 - $2000'), ('2000-3000', '$2000 - $3000'), ('3000>', '$3000+')], max_length=10)),
                ('skill_requirements', models.TextField()),
                ('minimum_education_requirements', models.TextField()),
                ('hide_budget', models.BooleanField(default=False)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_expectations', models.IntegerField()),
                ('applicant_experiences', models.TextField()),
                ('applicant_education', models.TextField()),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
    ]
