# Generated by Django 4.2.3 on 2023-07-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_education_requirements',
            field=models.CharField(max_length=20),
        ),
    ]
