# Generated by Django 4.2.3 on 2023-07-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='hide_budget',
            new_name='hide_salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='minimum_education_requirements',
            new_name='minimum_education',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='budget',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='title',
        ),
    ]
