# Generated by Django 4.2.3 on 2023-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_company_description_companyprofile_description_and_more'),
        ('jobs', '0003_rename_hide_budget_job_hide_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant_profile')},
        ),
    ]
