# Generated by Django 4.2.3 on 2023-07-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_job_finished_job_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_education',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='salary_expectations',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_education',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=30),
        ),
    ]
