# Generated by Django 4.2.3 on 2023-07-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_applicant_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='compatibility',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
